// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ekzVar.Data;

#nullable disable

namespace ekzVar.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("ekzVar.Models.Materials", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("ekzVar.Models.Oboi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OsnovaMaterialId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PokritieMaterialId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OsnovaMaterialId");

                    b.HasIndex("PokritieMaterialId");

                    b.ToTable("Oboi");
                });

            modelBuilder.Entity("ekzVar.Models.Oboi", b =>
                {
                    b.HasOne("ekzVar.Models.Materials", "OsnovaMaterial")
                        .WithMany()
                        .HasForeignKey("OsnovaMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ekzVar.Models.Materials", "PokritieMaterial")
                        .WithMany()
                        .HasForeignKey("PokritieMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OsnovaMaterial");

                    b.Navigation("PokritieMaterial");
                });
#pragma warning restore 612, 618
        }
    }
}
